### ISSUE TITLE
how i can define my custom objects 

### ISSUE THREAD

**Issue by Elabbasy00** [tweigel-dev/python-tuio#11]
I am using reacT vision Tuio Simulator for experiment purpose 
How do I define my own objects for the actual touch screen experience

**Comment by Elabbasy00** [comment]
This is exactly what I want
What I'm doing right now is downloading a desktop app made by tabel makers in order to get the data

**Comment by tweigel-dev** [comment]
Hay, did you figure out how you can use tuio for your purpose or is the issue still open?
@Elabbasy00

**Comment by Elabbasy00** [comment]
I haven't found a solution yet, but you can lock it
Thank you so much
