### ISSUE TITLE
Remove tuio cursor

### ISSUE THREAD

**Issue by adri1177** [tweigel-dev/python-tuio#14]
Hello,
I have been testing your solution, but when I send a TUIO cursor it never gets removed from the client. I can move it, but once I remove it from the server, the client thinks there is one cursor on the last position.

'''
        server = TuioServer(self.ip, self.port)
        cursor = Cursor(random.randint(0, 500))  # sets session_id to random
        cursor.velocity = (0.2, 0.2)
        cursor.motion_acceleration = 0.1
        server.cursors.append(cursor)
        cursor.position = (x, y)
        server.send_bundle()
        time.sleep(0.1)
        cursor.position = (x, y)
        server.send_bundle()
        time.sleep(0.1)
        server.cursors.remove(cursor)
        print(server.cursors)
        server.send_bundle()
        time.sleep(0.2)
'''

How do you handle that?

**Comment by tweigel-dev** [comment]
Hay, 
you found a bug. Thanks for the issue !
I changed the behavior if the lists are empty. 
https://github.com/tweigel-dev/python-tuio/pull/16
If the Pipeline succeeds you should be able to download the new version via pip.

**Comment by adri1177** [comment]
yes, now it is fixed and working. Thanks.
